config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  #resources :articles Gives us access to all the routes
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
    belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25}
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false },length: {maximum: 25}, format: { with: VALID_EMAIL_REGEX }
    has_many :articles, dependent: :destroy
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = 'You must be logged in to perform that action'
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def show
        
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        # We need this for the first time the page loads so that we can have something in our article
        @article = Article.new
    end

    def edit
        
    end

    def create
        @article = Article.new(article_params)
        # Code below Assign every article to the first user of the article
        # @article.user = User.first
        @article.user = current_user
        if @article.save
        # redirect to articles show page
            flash[:notice] = "Alert was created successfully."
            redirect_to @article
        # render @article, status: :unprocessable_entity
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def update
        # Find article that needs to be edited
        # The function that does this is below
        
        #  update the article. We need to white list and make title, and descriptin available to use
        if @article.update(article_params)
            flash[:notice] = 'Article was updated successfully.'
            redirect_to @article
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        # Find article to be deleted based on the id
        # The function that does this is below
        
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article 
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

    def require_same_user 
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    def new 
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfuly created"
            redirect_to @category
        else
            render 'new', status: :unprocessable_entity
        end 
    end

    def show 
        @category = Category.find(params[:id])
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    private 
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
  end

  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user  && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else
      flash.now[:alert] = 'There was something wrong with your details'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil 
    flash[:notice] = 'logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account information is successfuly updated'
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha blog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and articles deleted"
    redirect_to articles_path
  end 

  private 

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user 
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { :size => 80 })
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "http://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded")
    end

    #Before transfering it to the application controller
    #def current_user 
     #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
    #end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="container">
    <%= render 'shared/errors', obj: @article %>
    <%= form_with(model: @article, local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :title, class: "col-2 col-form-label" %>
            <div class="col-10">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
            </div>
        </div>
         <div class="form-group row">
            <%= f.label :description, class: "col-2 col-form-label" %>
            <div class="col-10">
                <%= f.text_area :description, class: "form-control", placeholder: "Description of article" %>
            </div>
        </div>
        <div class="form-group row">
             <%= f.submit class: "btn btn-light btn-lg"%><br />
        </div>
    <% end %>
</div>

     

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit a new article</h1>

<%= render 'form' %>

<%= link_to 'Cancel edit && Return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing All Articles</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<div class="container">
    <% @articles.each do |article| %>
        <div class="card text-center ">
    <div class="card-header mt-4">
        by <%= article.user.username if article.user%>
        </div>
        <div class="card-body mt-4">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success"%></h5>
            <p class="card-text"><%= truncate(article.description, length: 100)%>.</p>
            <%= link_to 'View', article_path(article), class: "btn btn-success"%>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%=link_to 'Edit', edit_article_path(article), class: "btn btn-info" %>
                <%= link_to 'Delete', article_path(article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
            <% end %>
        </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at)%> ago, edited <%= time_ago_in_words(article.updated_at)%> ago</small>
        </div>
        </div>
    <% end %>
</div>

<p>
    <%= link_to 'Create new article', new_article_path %>
</p>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<% if false %>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
   
        <tr>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Delete', article_path(article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></td>
        </tr>

    </tbody>
</table>
<% end %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

<%= render 'form'  %>

<%= link_to 'Return to articles listing', articles_path %>
     

app/views/articles/show.html.erb
<div class="container">
<h1 class="text-center text-success"><%= @article.title%></h1>
    <div class="card text-center ">
        <div class="card-header mt-4">
            by <%= @article.user.username if @article.user%>
            <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
            </div>
            <div class="card-body mt-4">
                <div class="card-text text-left"><%= simple_format(@article.description)%>.</div>
                <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                    <%=link_to 'Edit', edit_article_path(@article), class: "btn btn-info" %>
                    <%= link_to 'Delete', article_path(@article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(@article.created_at)%> ago, edited <%= time_ago_in_words(@article.updated_at)%> ago</small>
            </div>
            </div>
    </div>
</div>

<%= link_to 'Edit', edit_article_path(@article) %> | 
<%= link_to 'Delete', article_path(@article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %> |
<%= link_to 'Return to articles listing', articles_path %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Listing All Categories</h1>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>
<div class="container">
    <% @categories.each do |category| %>
        <div class="card text-center ">
            <div class="card-body mt-4">
                <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success"%></h5>
            </div>
            <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(category.created_at)%> ago</small>
            </div>
        </div>
    <% end %>
</div>

<p>
    <%= link_to 'Create new article', new_article_path %>
</p>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<% if false %>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
   
        <tr>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Delete', article_path(article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></td>
        </tr>

    </tbody>
</table>
<% end %>

app/views/categories/new.html.erb
<h1>Create a new Category</h1>

<div class="container">
    <%= render 'shared/errors', obj: @category %>
    <%= form_with(model: @category, local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :name, "Category name", class: "col-2 col-form-label" %>
            <div class="col-10">
                <%= f.text_field :name, class: "form-control", placeholder: "Enter a name" %>
            </div>
        </div>
        <div class="form-group row">
             <%= f.submit class: "btn btn-light btn-lg"%><br />
        </div>
    <% end %>
</div>
<div class="mb-3">
    <%= link_to 'Cancel edit && Return to articles listing', articles_path %>
</div>

     

app/views/categories/show.html.erb
<h1 class="text-center mt-4">category: <%= @category.name %></h1>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
     <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>" role="alert">
        <%= msg%>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to "Articles", articles_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
                <%= link_to "Bloggers", users_path, class: "nav-link" %>
            </li>
            <% if logged_in? %>
                <li class="nav-item active">
                    <%= '(Admin)' if current_user.admin? %><%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
                </li>
                <li class="nav-item active">
                    <%= link_to 'Edit User', edit_user_path(current_user), class: "nav-link" %>
                </li>
                <li class="nav-item active">
                    <%= link_to "Log out", logout_path , data: { turbo_method: :delete }, class: "nav-link" %>
                </li>
                <li class="nav-item active">
                    <%= link_to "Delete Profile", user_path(current_user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "nav-link" %>
                </li>
            <% else %>
                <li class="nav-item active">
                    <%= link_to "Log in", login_path, class: "nav-link"%>
                </li>
                <li class="nav-item active">
                    <%= link_to "Sign Up", signup_path, class: "nav-link"%>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is an about page</h1>
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container">
<h1>Welcome to the home page</h1>
    <div class="jumbotron">
        <h1 class="display-4">Blog</h1>
        <p class="lead">This is a certain blog</p>
        <hr class="my-4">
        <p>This is the content of a certain blog.</p>
        <p class="lead">
        <%= link_to 'Sign Up', signup_path, class: "btn btn-primary" %>
        </p>
    </div>
    <%= link_to 'Articles listing', articles_path %> | 
    <%= link_to 'Return to articles listing', articles_path %>
    <%= link_to 'About page', about_path %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>    
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase%> from being saved</h4>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <%= render 'shared/errors', obj: @user %>
    <%= form_with(model: @user, local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :username, class: "col-2 col-form-label" %>
            <div class="col-10">
                <%= f.text_field :username, class: "form-control", placeholder: "Enter a username" %>
            </div>
        </div>
         <div class="form-group row">
            <%= f.label :email, class: "col-2 col-form-label" %>
            <div class="col-10">
                <%= f.email_field :email, class: "form-control", placeholder: "Enter your email address" %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :password, class: "col-2 col-form-label" %>
            <div class="col-10">
                <%= f.password_field :password, class: "form-control", placeholder: "Choose a password" %>
            </div>
        </div>
        <div class="form-group row">
             <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-light btn-lg")%><br />
        </div>
    <% end %>
</div>
<div class="mb-3">
    <%= link_to 'Cancel edit && Return to articles listing', articles_path %>
</div>

     

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div class="container">
    <% @users.each do |user| %>
        <div class="card text-center ">
        <div class="card-header mt-4">
        <%= link_to user.username, user%>
        </div>
        <div class="card-body mt-4">
            <h5 class="card-title"><%= link_to gravatar_for(user, :size => 150), user %></h5>
            <p class="card-text"><%= pluralize(user.articles.count, 'article')%>.</p>
            <%= link_to 'View Profile', user, class: "btn btn-success"%>
            <% if logged_in? && (user == current_user || current_user.admin?) %>
                <%=link_to 'Edit Profile', edit_user_path(user), class: "btn btn-info" %>
                <%=link_to 'Delete Profile', user_path(user), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
            <% end %>
        </div>
        <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at)%> ago</small>
        </div>
        </div>
    <% end %>
</div>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up for alpha blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%=@user.username%> Profile</h1>
<%# Add this to your helpers folder %>
<%= gravatar_for @user, size: 200, class: "text-center"%>

<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to 'Edit your profile', edit_user_path(@user), class: "btn btn-info mt-4"%>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<div class="container">
    <% @articles.each do |article| %>
        <div class="card text-center ">
    <div class="card-header mt-4">
        by <%= article.user.username if article.user%>
        </div>
        <div class="card-body mt-4">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success"%></h5>
            <p class="card-text"><%= truncate(article.description, length: 100)%>.</p>
            <%= link_to 'View', article_path(article), class: "btn btn-success"%>
            <%=link_to 'Edit', edit_article_path(article), class: "btn btn-info" %>
            <%= link_to 'Delete', article_path(article), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
        </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at)%> ago, edited <%= time_ago_in_words(article.updated_at)%> ago</small>
        </div>
        </div>
    <% end %>
</div>
<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>





<% if false %>
  <div>
    <%= link_to "Edit this user", edit_user_path(@user) %> |
    <%= link_to "Back to users", users_path %>

    <%= button_to "Destroy this user", @user, method: :delete %>
  </div>
<% end %>